import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowLeft, Check, CircleAlert, Database, LockKeyhole, ShieldCheck, UserRound } from "lucide-react";
import type { Project, ProjectCaseStudy } from "@/data/projects";
import { TechBadge } from "@/components/ui/TechBadge";
import { sectionContainer, sectionLabel, sectionPadding, sectionTitle } from "@/components/ui/sectionLayout";

type Props = { project: Project; caseStudy: ProjectCaseStudy };
const card = "rounded-2xl border border-pink-200 bg-white p-6 shadow-sm shadow-pink-100 lg:rounded-3xl lg:p-8";

function Heading({ label, title }: { label: string; title: string }) {
  return <div className="mb-8 max-w-4xl lg:mb-10"><p className={sectionLabel}>{label}</p><h2 className={sectionTitle}>{title}</h2></div>;
}

function CheckList({ items }: { items: string[] }) {
  return <ul className="grid gap-3 sm:grid-cols-2">{items.map(item => <li key={item} className="flex gap-3 text-sm leading-relaxed text-pink-800"><Check className="mt-0.5 h-4 w-4 shrink-0 text-pink-500" aria-hidden="true" /><span>{item}</span></li>)}</ul>;
}

export function ElectionSystemProjectDetail({ project, caseStudy }: Props) {
  const details = caseStudy.electionCaseStudy;
  if (!details || !caseStudy.overview) return null;

  return <main className="bg-pink-50 pt-28 text-pink-950 md:pt-[4.75rem]"><article>
    <header className={`grid-bg relative overflow-hidden ${sectionPadding}`}><div className="pointer-events-none absolute -right-24 top-16 h-80 w-80 rounded-full bg-rose-300/40 blur-3xl" /><div className={`relative ${sectionContainer}`}>
      <Link href="/#projects" className="mb-10 inline-flex items-center gap-2 rounded-full border border-pink-200 bg-white px-4 py-2 font-mono text-xs font-semibold uppercase tracking-wider text-pink-700 shadow-sm hover:bg-pink-50 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-pink-500"><ArrowLeft className="h-4 w-4" /> Back to projects</Link>
      <div className="grid items-center gap-10 lg:grid-cols-[1.02fr_0.98fr] lg:gap-14"><div><p className={sectionLabel}>{caseStudy.eyebrow}</p><h1 className="text-5xl font-bold tracking-tight sm:text-6xl lg:text-7xl">{caseStudy.title}</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-pink-800 lg:text-xl">{caseStudy.hero?.intro}</p><div className="mt-6 flex flex-wrap gap-2">{project.technologies?.map(tech => <TechBadge key={tech} label={tech} />)}</div><div className="mt-8 flex flex-wrap gap-3"><span className="inline-flex items-center gap-2 rounded-full border border-pink-200 bg-white px-4 py-2 text-sm font-medium"><span className="h-2 w-2 rounded-full bg-pink-500" />{caseStudy.status}</span><span className="inline-flex items-center gap-2 rounded-full border border-dashed border-pink-300 bg-white px-4 py-2 text-sm font-medium text-pink-700"><CircleAlert className="h-4 w-4" />Source repository undergoing security cleanup</span></div></div>
        <figure className="overflow-hidden rounded-3xl border border-pink-200 bg-white p-3 shadow-xl shadow-pink-200/60"><div className="relative aspect-[16/10] overflow-hidden rounded-2xl bg-slate-100"><Image src="/projects/election-system/election-management.png" alt={caseStudy.heroImageAlt ?? "Election management interface"} fill priority className="object-cover" sizes="(max-width: 1024px) 100vw, 48vw" /></div><figcaption className="px-3 pb-1 pt-3 text-center text-xs text-pink-700">Administrative election and ballot management using sample data</figcaption></figure>
      </div>
    </div></header>

    <section className={`bg-white ${sectionPadding}`}><div className={sectionContainer}><Heading label="Project overview" title={caseStudy.overview.heading} /><div className="grid gap-5 text-base leading-relaxed text-pink-800 lg:grid-cols-3">{caseStudy.overview.paragraphs.map(p => <p key={p}>{p}</p>)}</div></div></section>
    <section className={`bg-rose-50/60 ${sectionPadding}`}><div className={sectionContainer}><Heading label="Collaboration" title={details.scope.heading} /><div className="grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><p className="text-lg leading-relaxed text-pink-800">{details.scope.description}</p><div className={card}><CheckList items={details.scope.items} /></div></div></div></section>

    <section className={`bg-white ${sectionPadding}`}><div className={sectionContainer}><Heading label="User roles" title="Different Responsibilities, Different Workflows" /><div className="grid gap-6 lg:grid-cols-3">{details.roles.map(role => <div key={role.title} className={card}><UserRound className="mb-4 h-7 w-7 text-pink-500" /><h3 className="mb-5 text-2xl font-bold">{role.title}</h3><ul className="space-y-3">{role.items.map(item => <li key={item} className="flex gap-2 text-sm leading-relaxed text-pink-800"><Check className="mt-0.5 h-4 w-4 shrink-0 text-pink-500" />{item}</li>)}</ul></div>)}</div></div></section>

    <section className={`bg-rose-50/60 ${sectionPadding}`}><div className={sectionContainer}><Heading label="Administration" title={details.configuration.heading} /><div className="grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><div><div className={card}><CheckList items={details.configuration.items} /></div><p className="mt-5 leading-relaxed text-pink-800">{details.configuration.description}</p></div><div className="grid gap-5 sm:grid-cols-2">{[{src:"/projects/election-system/election-management.png",alt:"Election administration page showing sample election configuration",caption:"Election and ballot management"},{src:"/projects/election-system/precinct-associations.png",alt:"Interface for connecting sample elections with eligible precincts",caption:"Election–precinct associations"}].map(image => <figure key={image.src} className="overflow-hidden rounded-2xl border border-pink-200 bg-white"><div className="relative aspect-[4/3]"><Image src={image.src} alt={image.alt} fill className="object-cover object-top" sizes="(max-width: 640px) 100vw, 25vw" /></div><figcaption className="p-3 text-sm text-pink-700">{image.caption}</figcaption></figure>)}</div></div></div></section>

    <section className={`bg-white ${sectionPadding}`}><div className={sectionContainer}><Heading label="Voting workflow" title="From Precinct Eligibility to Ballot Submission" /><ol className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{details.votingFlow.map((step, i) => <li key={step} className="rounded-2xl border border-pink-200 bg-pink-50 p-4"><span className="mb-3 flex h-8 w-8 items-center justify-center rounded-full bg-pink-500 font-mono text-xs font-bold text-white">{i + 1}</span><span className="text-sm leading-relaxed text-pink-900">{step}</span></li>)}</ol><p className="mt-6 rounded-2xl border border-pink-200 bg-white p-5 text-sm leading-relaxed text-pink-800">This is the implemented prototype workflow—not a claim that the application meets the security, legal, accessibility, audit, or certification requirements of a real public election system.</p></div></section>

    <section className={`grid-bg ${sectionPadding}`}><div className={sectionContainer}><Heading label="Election lifecycle" title="Managing Ballots Before, During, and After Voting" /><ol className="grid gap-3 md:grid-cols-4">{details.lifecycle.map((step, i) => <li key={step} className="flex flex-col items-center text-center"><div className="w-full rounded-2xl border border-pink-200 bg-white p-4 text-sm font-semibold shadow-sm"><span className="block font-mono text-xs text-pink-500">{String(i + 1).padStart(2,"0")}</span>{step}</div>{i < details.lifecycle.length - 1 && <ArrowDown className="my-2 h-4 w-4 text-pink-400 md:hidden" />}</li>)}</ol><p className="mt-7 text-pink-800">A ballot must be verified and within its election date range before activation. Managers can activate, deactivate, count, and review precinct ballots; results then pass through verification before an administrator releases them publicly.</p></div></section>

    <section className={`bg-white ${sectionPadding}`}><div className={sectionContainer}><Heading label="Database" title="A Relational Model for Election Operations" /><p className="mb-8 max-w-4xl text-lg leading-relaxed text-pink-800">{details.database.description}</p><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{details.database.domains.map(domain => <div key={domain.title} className={card}><Database className="mb-4 h-6 w-6 text-pink-500" /><h3 className="mb-3 text-lg font-bold">{domain.title}</h3><ul className="space-y-2 text-sm text-pink-800">{domain.items.map(item => <li key={item}>• {item}</li>)}</ul></div>)}</div></div></section>

    <section className={`bg-rose-50/60 ${sectionPadding}`}><div className={sectionContainer}><Heading label="Account controls" title="Role-Based Access and Account Verification" /><div className="grid gap-8 lg:grid-cols-[1.15fr_0.85fr]"><div className={card}><CheckList items={details.controls} /></div><div><LockKeyhole className="mb-4 h-8 w-8 text-pink-500" /><p className="leading-relaxed text-pink-800">These implemented controls demonstrate role-based application design, but they are not sufficient evidence of production election security. The prototype does not claim multifactor authentication, identity-document verification, encrypted ballots, cryptographic vote verification, or end-to-end verifiability.</p></div></div></div></section>

    <section className={`bg-white ${sectionPadding}`}><div className={sectionContainer}><Heading label="Results" title="Separating Internal Counts from Public Results" /><div className="grid gap-8 lg:grid-cols-2"><p className="text-lg leading-relaxed text-pink-800">{details.results}</p><div className={card}><h3 className="mb-4 text-lg font-bold">Verified pytest behaviors</h3><CheckList items={details.tests.slice(5)} /></div></div></div></section>

    <section className={`bg-rose-50/60 ${sectionPadding}`}><div className={sectionContainer}><Heading label="Interface" title="Administrative and Voter Workflows" /><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">{details.gallery.filter(image => !image.src.includes("election-management") && !image.src.includes("precinct-associations")).map(image => <figure key={image.src} className="overflow-hidden rounded-3xl border border-pink-200 bg-white shadow-sm"><div className="relative aspect-[4/3] bg-slate-100"><Image src={image.src} alt={image.alt} fill className="object-cover object-top" sizes="(max-width: 768px) 100vw, 50vw" /></div><figcaption className="p-4 text-sm leading-relaxed text-pink-700">{image.caption}</figcaption></figure>)}</div></div></section>

    <section className={`bg-white ${sectionPadding}`}><div className={sectionContainer}><Heading label="Testing" title="Checking Election and Permission Rules" /><div className={card}><CheckList items={details.tests.slice(0,5)} /></div><p className="mt-5 text-sm text-pink-700">The repository includes pytest coverage for these areas; no coverage percentage is shown because it was not recalculated.</p></div></section>

    <section className={`bg-rose-50/60 ${sectionPadding}`}><div className={sectionContainer}><Heading label="Reflection" title="Challenges in Modeling a High-Stakes Workflow" /><div className="grid gap-5 md:grid-cols-2">{details.challenges.map(item => <div key={item.title} className={card}><ShieldCheck className="mb-4 h-6 w-6 text-pink-500" /><h3 className="mb-3 text-xl font-bold">{item.title}</h3><p className="text-sm leading-relaxed text-pink-800">{item.description}</p></div>)}</div><p className="mt-8 max-w-4xl text-lg leading-relaxed text-pink-800">{details.conclusion}</p></div></section>

    <section className={`bg-white ${sectionPadding}`}><div className={sectionContainer}><Heading label="Technology stack" title="Tools Behind the Prototype" /><ul className="flex flex-wrap gap-3">{details.technologies.map(item => <li key={item}><TechBadge label={item} /></li>)}</ul><div className="mt-12"><Heading label="Skills" title="Skills Demonstrated" /><ul className="flex flex-wrap gap-3">{details.skills.map(item => <li key={item}><TechBadge label={item} /></li>)}</ul></div></div></section>

    <section className="bg-pink-950 py-14 text-white"><div className={`${sectionContainer} flex flex-col gap-5 px-6 sm:flex-row sm:items-center sm:justify-between sm:px-8 lg:px-12`}><div><p className="font-mono text-xs uppercase tracking-widest text-pink-300">Completed prototype</p><h2 className="mt-2 text-2xl font-bold">Explore more project work</h2><p className="mt-2 text-sm text-pink-200">Source repository undergoing security cleanup</p></div><Link href="/#projects" className="inline-flex w-fit items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-semibold text-pink-700 hover:bg-pink-50 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-white"><ArrowLeft className="h-4 w-4" /> Back to Projects</Link></div></section>
  </article></main>;
}
